# [실습] 지도를 이용한 데이터 시각화하기

##### [실습] 지도에 우리집 표시하기
##### [미션] 여행가고 싶은 장소(국내외) 3곳을 지도에 다른 색상 마커로 표시하기
##### [실습] (나의) 구글 Location History 데이터 지도에 표시하기
##### [실습] 우리나라 행정구역 경계 지도에 표시하기
##### [실습] 서울지역 구별 인구수 지도에 시각화하기
##### [미션] 충청남도 지역별 인구수 지도에 시각화하기

-------------------------------

### 지도에 표시하기 위해 필요한 정보
- **위도(Latitude)**: 가로선, 적도를 기준으로 북쪽/남쪽으로 얼마나 떨어져 있는지 나타내는 위치, 위도 1도는 대략 111km, 
- **경도(longitude)**: 세로선, 그리니치 천문대를 기준으로 동/서를 세로로 표시하는 선, 오른쪽 동경(East~180)/왼쪽 서경(West~180)

In [8]:
# 인터넷에 있는 이미지 보여주기
from IPython.display import Image
Image(url='http://4.bp.blogspot.com/-7nTuhDQ2gSE/VYgQiE8sJzI/AAAAAAAAALw/JFVQKIhZyF4/s1600/This_is_a_basic_photo_showing_that_latitude_lines_are_horizontal_and_longitude_lines_are_vertical-_2014-07-25_20-36.jpg'
     , width=400, height=300)

- **우리나라의 위도 경도 **
> 위도(33 ~ 43), 경도(124 ~ 132)

In [9]:
Image(url='https://mblogthumb-phinf.pstatic.net/MjAxOTA3MTJfMTgg/MDAxNTYyOTAxMzQ0MzE0.KPkhwGuXiIxf5gKHa28kdazfvAFi8x_8pYqQf5wCgIIg.bFcsxsI-MmUaKUW_zBJWhCE6Z7mbbaI4z7a7NW6G2wog.PNG.lkokvse78/image.png?type=w800'
          , width=400, height=300)

--------------

### [실습] 지도에 우리집 표시하기

#### 지도 라이브러리
- https://python-visualization.github.io/folium/

#### 1. 지도 라이브러리 folium 설치

In [1]:
!pip install folium

Requirement already satisfied: folium in c:\python\python39\lib\site-packages (0.12.1.post1)
Requirement already satisfied: jinja2>=2.9 in c:\python\python39\lib\site-packages (from folium) (3.1.2)
Requirement already satisfied: branca>=0.3.0 in c:\python\python39\lib\site-packages (from folium) (0.5.0)
Requirement already satisfied: requests in c:\python\python39\lib\site-packages (from folium) (2.28.1)
Requirement already satisfied: numpy in c:\python\python39\lib\site-packages (from folium) (1.23.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\python\python39\lib\site-packages (from jinja2>=2.9->folium) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\python\python39\lib\site-packages (from requests->folium) (1.26.9)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\python\python39\lib\site-packages (from requests->folium) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\python\python39\lib\site-packages (from requests->folium) (2022.6.15)
Requirement already satisfied: idna<4,>=2.5 in c:\python\python39\lib\site-packages (from requests->folium) (3.3)

In [2]:
import folium

folium.__version__

'0.12.1.post1'

#### 2. 우리집 주소 지도에 표시하기
- 구글 지도 또는 네이버 지도 등에서 우리집 위도&경도 값 확인하기
- 내장 map 종류: ( ‘Stamen Terrain’, ‘Stamen Toner')
 -- ‘Mapbox Bright’, 와 ‘Mapbox Control room tiles’ 은 등록키가 있어야함.

In [4]:
import folium
import webbrowser

# 우리집 [위도,경도]=[Latitude, longitude]
data = {'우리집': [36.7899199, 127.1072194] }

m = folium.Map(location=data['우리집'], zoom_start=16)
m = folium.Map(location=[36.7899199, 127.1072194], zoom_start=16)

# m = folium.Map(location=data['우리집'], zoom_start=16,
#               tiles='Mapbox Control room tiles')

folium.Marker(location = data['우리집'],
              popup = '충남콘텐츠기업지원센터', 
              icon=folium.Icon(color='red', icon='star')
).add_to(m)

m

#### 3. 우리 집 반경에 CircleMarker 표시하기
- location Point [위도, 경도] 를 중심으로 radius 만큼의 원을 그립

In [5]:
folium.CircleMarker(
    location= data['우리집'],
    radius = 100,      # 원 크기
    fill=True,         # 원 칠하기
    color='#3366ff',   # 원 선 색상
    fill_color='#ff3366', # 원 내부 색상
    popup='CircleMarker popup',
    tooltip = '우리집'
).add_to(m)

m

#### 4. html 파일로 저장하기

In [6]:
# html 파일로 저장하기
m.save('data/map_myhouse.html')
webbrowser.open('c:/python/0_joys/data/myhouse.html') # fullpath를 사용해야 오류가 없다

True

### [미션] 여행가고 싶은 장소(국내외) 3곳을 지도에 다른 색상 마커로 표시하기

- 영국-내셔널 갤러리: 51.508929,-0.128299
- 뉴욕-브로드웨이: 40.8124199,-73.9627283
- 로마-트레비 분수: 41.9010333,12.4810789
- tiles='Mapbox'
> - Stamen Terrain: 녹색 지도
> - Stamen Toner: 흑백 토너

In [8]:
buckets = {'영국-내셔널 갤러리': [51.508929,-0.128299],
           '뉴욕-브로드웨이': [40.8124199,-73.9627283],
           '로마-트레비 분수': [41.9010333,12.4810789],
          }

m = folium.Map(location= [41.9010333, 12.4810789], 
               zoom_start=2, 
               tiles='Stamen Toner')

folium.Marker(location= buckets['영국-내셔널 갤러리'],
              icon=folium.Icon(icon='glyphicon glyphicon-thumbs-up',
                                   color='purple', icon_color='white',),
              popup='영국-내셔널 갤러리',
              tooltip = '1st travel'
).add_to(m)
folium.Marker(location= buckets['뉴욕-브로드웨이'],
              icon=folium.Icon(icon='info-sign', color='green'),
              popup='뉴욕 브로드웨이',
              tooltip = '2nd travel'
).add_to(m)
folium.Marker(location= buckets['로마-트레비 분수'],
              icon=folium.Icon(icon='cloud', color='red'),
              popup='로마 트레비 분수',
              tooltip = '3rd travel'
).add_to(m)

m.save('data/map_mytravel.html')
webbrowser.open('c:/python/0_joys/data/map_mytravel.html') # fullpath를 사용해야 오류가 없다

True

----------------------

--------------

### [실습] (나의) 구글 Location History 데이터 지도에 표시하기

#### 참고 글
https://betterprogramming.pub/loading-location-history-places-from-google-timeline-into-pandas-and-csv-c26cb0ac5e89

#### 1. 구글 Location History 데이터 다운로드
- 구글 크롬 브라우저에 로그인 된 상태에서
- https://takeout.google.com/settings/takeout 사이트로 이동하기
- 모두 체크를 해제시키고 **위치 기록** 만 체크표시하고 
- takeout-20220620T021113Z-001.zip 파일이 다운로드 된다.

#### 2. 필요한 라이브러리 설치하기
설치시 오류가 발생하면 윈도우 명령프롬프트창에서 timezonefinder 설치를 진행해 본다.

In [9]:
# 시간대 확인 라이브러리
!pip install timezonefinder

Requirement already satisfied: timezonefinder in c:\python\python39\lib\site-packages (6.0.1)
Requirement already satisfied: numpy>=1.20.3 in c:\python\python39\lib\site-packages (from timezonefinder) (1.23.0)
Requirement already satisfied: h3>=3.7.3 in c:\python\python39\lib\site-packages (from timezonefinder) (3.7.4)

In [8]:
# 경도, 위도값으로 시간대 정보 가져오기
from timezonefinder import TimezoneFinder

tzf= TimezoneFinder()
tz = tzf.timezone_at(lng=128, lat=38)  # 'Asia/Seoul'
#tz = tzf.timezone_at(lng=13.358, lat=52.5061)  # 'Europe/Berlin'
tz

'Asia/Seoul'

#### 3.나의 Local History데이터 정보를 딕셔너리타입으로 변환하기

In [10]:
from zipfile import ZipFile
import pandas as pd
import json
from timezonefinder import TimezoneFinder

In [11]:
# path to Google Location History takeout file
history_data_file = "data/takeout-20220708T064358Z-001.zip"

# store all places into this array
place_visits = []

with ZipFile(history_data_file) as myzip:
    for file in myzip.filelist[:]:
        filename = file.filename
        
        if "Semantic Location History" in filename:
            # process all files in "Semantic Location History" directory
            history_json = json.load(myzip.open(filename))

            for timeline_object in history_json["timelineObjects"]:
               
                if "placeVisit" in timeline_object:
                    place_visit_json = timeline_object["placeVisit"]
                    
                    # skip places without geographical coordinates
                    if not "location" in place_visit_json or not "latitudeE7" in place_visit_json["location"]:
                        continue
                    
                    place_visit = {
                        "placeId": place_visit_json["location"]["placeId"],
                        "locationConfidence": place_visit_json["location"]["locationConfidence"],
                        "startTimestamp": place_visit_json["duration"]["startTimestamp"],
                        "endTimestamp": place_visit_json["duration"]["endTimestamp"],
                        "placeVisitImportance": place_visit_json["placeVisitImportance"],
                        "placeVisitType": place_visit_json["placeVisitType"],
                        "latitudeE7": place_visit_json["location"]["latitudeE7"],
                        "longitudeE7": place_visit_json["location"]["longitudeE7"],
                    }
                    
                    for optional_field in ["centerLatE7", "centerLngE7"]:
                        if optional_field in place_visit_json:
                            place_visit[optional_field] = place_visit_json[optional_field]
                        else:
                            place_visit[optional_field] = None
                    
                    for optional_field in ["name", "address"]:
                        if optional_field in place_visit_json["location"]:
                            place_visit[optional_field] = place_visit_json["location"][optional_field]
                        else:
                            place_visit[optional_field] = None
                        
                    
                    place_visits.append(place_visit)

place_visit

{'placeId': 'ChIJiWKXIGxhezURSdDzm8-jpb0',
 'locationConfidence': 48.73679,
 'startTimestamp': '2022-05-30T10:50:56.788Z',
 'endTimestamp': '2022-06-01T03:59:57.914Z',
 'placeVisitImportance': 'MAIN',
 'placeVisitType': 'SINGLE_PLACE',
 'latitudeE7': 374308554,
 'longitudeE7': 1268842593,
 'centerLatE7': 374309204,
 'centerLngE7': 1268841654,
 'name': '501 광명역세권휴먼시아5단지',
 'address': '대한민국 광명시 소하2동'}

#### 4. DataFrame 형태로 변환하기

In [13]:
# 1.DataFrame형태로 변환하기
place_visits_df = pd.DataFrame(place_visits)
place_visits_df.head(2)


# 2.데이터 전처리하기
# convert to datetime type
place_visits_df["startTimestamp"] = pd.to_datetime(place_visits_df["startTimestamp"])
place_visits_df["endTimestamp"] = pd.to_datetime(place_visits_df["endTimestamp"])

# get geo coordinates as float value
place_visits_df["latitude"] = place_visits_df.latitudeE7/10**7   #(1E7 = 1e7 = 1x10^7 = 10**7)
place_visits_df["longitude"] = place_visits_df.longitudeE7/1e7
place_visits_df["centerLat"] = place_visits_df.centerLatE7/1E7
place_visits_df["centerLng"] = place_visits_df.centerLngE7/1E7
 
# add timezone based on geo coordinates
tf = TimezoneFinder()
place_visits_df["timezone"] = place_visits_df.apply(lambda row: tf.timezone_at(lng=row.longitude, lat=row.latitude), axis=1)

# convert UTC time to local timezone
place_visits_df['startTimestamp_local'] = place_visits_df.apply(lambda row: row.startTimestamp.tz_convert(row.timezone), axis=1)
place_visits_df['endTimestamp_local'] =place_visits_df.apply(lambda row: row.endTimestamp.tz_convert(row.timezone), axis=1)

# remove TZ info from datetime
place_visits_df['startTimestamp_local'] = pd.to_datetime(place_visits_df['startTimestamp_local'].apply(lambda x: x.replace(tzinfo=None)))
place_visits_df['endTimestamp_local'] = pd.to_datetime(place_visits_df['endTimestamp_local'].apply(lambda x: x.replace(tzinfo=None)))

# add datetime parts as a separate column to data frame
for datetime_type in [("year", lambda x: x.year), ("month", lambda x: x.month), ("day", lambda x: x.day), ("hour", lambda x: x.hour), ("minute", lambda x: x.minute), ("weekday", lambda x: x.weekday)]:
    for tztype in ["", "_local"]:
        place_visits_df[f"{datetime_type[0]}{tztype}"] = datetime_type[1](place_visits_df[f"startTimestamp{tztype}"].dt)
        

place_visits_df.drop(columns=["latitudeE7", "longitudeE7", "centerLatE7", "centerLngE7"], inplace=True)
place_visits_df["duration"] = place_visits_df.endTimestamp - place_visits_df.startTimestamp
place_visits_df["duration_minutes"] = place_visits_df.duration.dt.total_seconds()/60


# 3. 파일로 저장하기
file = "data/place_visits.csv"
place_visits_df.to_csv(file, index=False)


place_visits_df.head(2)

,placeId,locationConfidence,startTimestamp,endTimestamp,placeVisitImportance,placeVisitType,name,address,latitude,longitude,...,day,day_local,hour,hour_local,minute,minute_local,weekday,weekday_local,duration,duration_minutes
0,ChIJz3TYfyNhezURMlQX2atTEbk,30.33175,2022-04-09 01:28:46.336000+00:00,2022-04-09 02:29:15.483000+00:00,MAIN,SINGLE_PLACE,Gwangmyeong Station U-Planet Desian,대한민국 경기도 광명시 양지로 7,37.418959,126.881490,...,9,9,1,10,28,28,5,5,0 days 01:00:29.147000,60.485783
1,ChIJpVT-WLBlezURI2UitKht3Ck,98.19835,2022-04-09 03:12:24.670000+00:00,2022-04-09 03:31:24.547000+00:00,MAIN,SINGLE_PLACE,안산농협 연꽃 로컬푸드,대한민국 경기도 시흥시 목감동 동서로 770,37.384360,126.830933,...,9,9,3,12,12,12,5,5,0 days 00:18:59.877000,18.997950

#### 5. (나의)Location History 지도에 표시하기

In [14]:
import folium
import webbrowser
import pandas as pd

# 파일 불러오기
# df = pd.read_csv(file)
df = place_visits_df


center = [37.4306881, 126.8845086]
m = folium.Map(location=center ,
                  zoom_start=6, 
                  width=750, 
                  height=500)

# df에서 위도&경도 정보 지도 Marker에 추가하기
folium.Marker(location=center, 
                popup='우리집', icon=folium.Icon(color='red', icon='star'),
                color='tomato', radius = 50,
).add_to(m)


# 구글 Location History 마커로 표시하기
for i, row in df.iterrows():    
    folium.Marker(location= [row['latitude'], row['longitude']], 
                  icon=folium.Icon(icon='cloud', color='green'),
                  popup=row['name']
    ).add_to(m)
    
m    

#html 파일로 저장하여 불러오기
m.save('data/map_google_lh.html')
webbrowser.open('C:/python/dataAnalysis/data/map_google_lh.html')

True

--------------------

### 우리나라 행정구역 경계 지도에 표시하기

####  1. 우리나라 행정구역 경계 데이터 다운로드하기
- https://github.com/southkorea/southkorea-maps 
- **Provinces (시도)** :  skorea-provinces-2018-geo.json  
- **Municipalities (시군구)** : skorea-municipalities-2018-geo.json

#### 2. 우리나라 행정구역 시/도 경계 표시하기

In [15]:
import folium
import json


file = 'data/skorea-provinces-2018-geo.json'
# file = 'data/skorea-municipalities-2018-geo.json'
rfile = open(file, 'r', encoding='utf-8').read()
jsonData = json.loads(rfile)

m = folium.Map(location=[37.566345, 126.977893], zoom_start=6)
folium.GeoJson(jsonData, name='json_data').add_to(m)
m

m.save('data/map_provinces.html')
webbrowser.open('c:/python/dataAnalysis/data/map_provinces.html') # fullpath를 사용해야 오류가 없다

True

-----------

### [실습] 서울지역 구별 인구수 지도에 시각화하기

#### 1. 데이터 준비하기

- 서울지역 행정구역 geocode데이터(json):
-- https://github.com/raqoon886/Local_HangJeongDong   <br>
-- hangjeongdong_서울특별시.geojson 
-- [url]'https://raw.githubusercontent.com/southkorea/seoul-maps/master/kostat/2013/json/seoul_municipalities_geo_simple.json'  <br><br>

- 서울지역 행정구역별 인구 데이터(csv): 
-- https://jumin.mois.go.kr/index.jsp
-- 202205_202205_주민등록인구및세대현황_월간_서울.csv

#### 2. 데이터 전처리하기
행정구역별 인구 데이터 필요한 부분만 추출하여 파일로 만들기

In [17]:
import pandas as pd

file = 'data/202205_202205_주민등록인구및세대현황_월간_서울.csv'
df = pd.read_csv(file, encoding='euc-kr')
df_t = df.copy()
df_t.head(2)
df_t

,행정구역,2022년05월_총인구수,2022년05월_세대수,2022년05월_세대당 인구,2022년05월_남자 인구수,2022년05월_여자 인구수,2022년05월_남여 비율
0,서울특별시 (1100000000),"9,496,887","4,460,604",2.13,"4,607,440","4,889,447",0.94
1,서울특별시 종로구 (1111000000),"143,850","73,822",1.95,"69,638","74,212",0.94
2,서울특별시 중구 (1114000000),"122,054","63,880",1.91,"59,368","62,686",0.95
3,서울특별시 용산구 (1117000000),"222,083","111,508",1.99,"106,666","115,417",0.92
4,서울특별시 성동구 (1120000000),"284,173","134,357",2.12,"138,373","145,800",0.95
...,...,...,...,...,...,...,...
21,서울특별시 관악구 (1162000000),"486,686","280,657",1.73,"244,628","242,058",1.01
22,서울특별시 서초구 (1165000000),"408,133","169,642",2.41,"195,056","213,077",0.92
23,서울특별시 강남구 (1168000000),"531,744","234,833",2.26,"254,347","277,397",0.92
24,서울특별시 송파구 (1171000000),"662,960","285,939",2.32,"319,461","343,499",0.93
25,서울특별시 강동구 (1174000000),"461,417","202,489",2.28,"226,062","235,355",0.96

In [18]:
# 불필요한 행 제거
df_t.drop( [df_t.index[0]], inplace=True  ) # 첫째행 삭제

In [19]:
# 불필요한 열 제거
df_t.drop( ['2022년05월_세대수','2022년05월_세대당 인구','2022년05월_남여 비율'], 
               axis=1, inplace=True ) # 특정 컬럼 삭제

# 컬럼명 변경
df_t.columns = ['행정구역','total','man','woman']
df_t.head(2)

                     행정구역    total     man   woman
1  서울특별시 종로구 (1111000000)  143,850  69,638  74,212
2   서울특별시 중구 (1114000000)  122,054  59,368  62,686

In [20]:
# 행정구역 시, 군 분리하기
# 특정 위치에 컬럼 추가
df_t.insert(1, 'sido', df_t['행정구역'].str.split(' ').str[0]) # 인덱스 1 위치에 추가
df_t.insert(2, 'name', df_t['행정구역'].str.split(' ').str[1]) # 인덱스 2 위치에 추가

# 맨 뒤에 컬럼 추가
# df_t['시'] = df_t['행정구역'].str.split(' ').str[0]
# df_t['군'] = df_t['행정구역'].str.split(' ').str[1]

# 숫자안에 콤마 제거 
df_t['total'] = df_t['total'].str.replace(pat=r',', repl=r'', regex=True)
df_t['man'] = df_t['man'].str.replace(pat=r',', repl=r'', regex=True)
df_t['woman'] = df_t['woman'].str.replace(pat=r',', repl=r'', regex=True)

df_t.head(2)

                     행정구역   sido name   total    man  woman
1  서울특별시 종로구 (1111000000)  서울특별시  종로구  143850  69638  74212
2   서울특별시 중구 (1114000000)  서울특별시   중구  122054  59368  62686

In [21]:
# 최종 불필요한 컬럼 제거
df_t.drop( ['행정구역'], axis=1, inplace=True ) # 특정 컬럼 삭제
df_t.head(2)

    sido name   total    man  woman
1  서울특별시  종로구  143850  69638  74212
2  서울특별시   중구  122054  59368  62686

In [22]:
# 파일로 저장하기
file = 'data/서울시_행정구역별_인구-m.csv'
df_t.to_csv(file)

#### 3. 지도에 표시하기

In [23]:
import pandas as pd

# 행정구역별 인구 데이터 불러오기.
df = pd.read_csv(file)
df.drop(['Unnamed: 0'], axis = 1, inplace = True)


# 행정구역별 Geocode 데이터 불러오기
# 방법1
geo_data = 'https://raw.githubusercontent.com/southkorea/seoul-maps/master/kostat/2013/json/seoul_municipalities_geo_simple.json'

# 방법2 (동 단위까지 있는 지리정보)
# import json
# file = 'data/hangjeongdong_서울특별시.geojson'
# with open(file, 'r') as f:
#     geo_data = json.load(f)

In [24]:
import folium

# 서울시 중심부의 위도, 경도 입니다.
center = [37.541, 126.986]

# 맵이 center 에 위치하고, zoom 레벨은 11로 시작하는 맵 m을 만듭니다.
m = folium.Map(location=center, tiles="OpenStreetMap", zoom_start=11)

#Choropleth 레이어를 만들고, 맵 m에 추가합니다.
folium.Choropleth(
    geo_data=geo_data,
    name='인구수',
    data=df,
    columns=('name', 'total'),
    key_on='feature.properties.name',
    fill_color='BuPu',
    legend_name='total',
).add_to(m)

# 맵 m을 출력합니다.
m

------------------------------------